apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: cert-manager-config
deploy:
  helm:
    releases:
      - name: cert-manager
        repo: https://charts.jetstack.io
        remoteChart: cert-manager
        namespace: cert-manager
        createNamespace: true
        version: v1.16.1
        setValues:
          installCRDs: true