datacenter: dc1
racks:
  - name: rack1
    members: 3
    storage:
      capacity: 15Gi
      storageClassName: openebs-hostpath
    resources:
      limits:
        cpu: 2       
        memory: 4Gi  
      requests:
        cpu: 1
        memory: 2Gi  